apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-devopsrn-cert
spec:
  secretName: devopsrn-secret
  issuerRef: 
    kind: ClusterIssuer
    name: letsencrypt-prd
  dnsNames:
    - "devopsrn.com.br"