apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-www-devopsrn-cert
spec:
  secretName: www-devopsrn-secret
  issuerRef: 
    kind: ClusterIssuer
    name: letsencrypt-prd
  dnsNames:
    - "www.devopsrn.com.br"